version: '3.9'

services:
  web:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./server/index.php:/var/www/html/index.php
      - ./server/styles.css:/var/www/html/styles.css
    depends_on:
      - db
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql